### PR TITLE
file field for season and full serial torrents

### PR DESCRIPTION
**Pull request by ivan1986**
Support file name for select episode in complete season or serial torrent
https://www.reddit.com/r/PopCornTime/comments/ek3vxm/russian_translated_films_and_serials_for/

### CODE REVIEW

**Comment by datnguyencse** [comment]
Thank you @ivan1986. It will be merged to the first release of this fork by next week.

**Comment by datnguyencse** [comment]
Hi @ivan1986, can you explain where are the value of `episodeData.torrents["x"].file` come from? our API server return only `.url` value for every series data and movie.

Because the api server do not return any data for `.file`, so your change doesn't make sense.

image

image

**Comment by ivan1986** [comment]
I add this in ru parser - https://github.com/ivan1986/popcorn-ru
for now addin spiders for yts and maybe thepirate bay
for now i check any language in interface and write spiders for other well-know trackers
also add title|owerview translation on any lang
because you add api url to setting it's easy to add servers for some other languages

**Comment by datnguyencse** [comment]
Ok I got it. Thank for your PR. I am going to release new version soon.

**Pull request merged**
